# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a352627769beff293b467402841f87432a87556a069525ea60abdb9a0f6fb71435f9fdb165a9c010513111500dd935fdfe91146f669e2dc380ad4ca8da974fd

test:
  secret_key_base: dcac40cb72e332382c7adac0b7dfd896c16c67e4f96df9d6be92dd0c30fe7c8f4b3141db8a66806456d7d53f2a36ad8e2456dcca0bdbce22a5f4d611f5189914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
